# Project: Projeto_bitcoin
# Makefile created by Dev-C++ 5.0.0.4

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = 
OBJ      = main.o login.o $(RES)
LINKOBJ  = main.o login.o $(RES)
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/lib" -L"C:/Program Files (x86)/Dev-Cpp/lib/gcc" -static-libstdc++ -static-libgcc  
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/include" 
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/include" 
BIN      = Projeto_bitcoin.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS   = $(INCS)  
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Projeto_bitcoin.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "Projeto_bitcoin.exe" $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

login.o: login.c
	$(CC) -c login.c -o login.o $(CFLAGS)
